ktor:
  deployment:
    port: 8080
  application:
    modules:
      - pro.aibar.sweatsketch.ApplicationKt.userModule

jwt:
  secret: ""
  refreshSecret: ""
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to SweatSketch service"